export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listing',
    route: '/listing',
    description: 'Verified businesses and services.',
    contentType: 'listing',
    enabled: true,
  },
  {
    key: 'classified',
    label: 'Classified',
    route: '/classified',
    description: 'Local offers, jobs, and deals.',
    contentType: 'classified',
    enabled: true,
  },
  {
    key: 'article',
    label: 'Article',
    route: '/article',
    description: 'Insights, blogs, and long-form content.',
    contentType: 'article',
    enabled: true,
  },
  {
    key: 'image',
    label: 'Image',
    route: '/image',
    description: 'Galleries and media-first posts.',
    contentType: 'image',
    enabled: true,
  },
  {
    key: 'profile',
    label: 'Profile',
    route: '/profile',
    description: 'Creator and business profiles.',
    contentType: 'profile',
    enabled: true,
  },
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Curated bookmarks and resources.',
    contentType: 'social',
    enabled: true,
  },
  {
    key: 'comment',
    label: 'Blog Commenting',
    route: '/blog',
    description: 'Commentary and response posts.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF Library',
    route: '/pdf',
    description: 'PDF resources and downloads.',
    contentType: 'pdf',
    enabled: true,
  },
  {
    key: 'org',
    label: 'Organizations',
    route: '/team',
    description: 'Organization profiles and directories.',
    contentType: 'profile',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
